# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/KANG Jian/Desktop/Underwater_OOK/Transmitter_Source_Code/ips/transmitter/transmitter.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==transmitter || ORIG_REF_NAME==transmitter} -quiet] -quiet

# IP: C:/Users/KANG Jian/Desktop/Underwater_OOK/Transmitter_Source_Code/ips/transmitter_system_clock_pll/transmitter_system_clock_pll.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==transmitter_system_clock_pll || ORIG_REF_NAME==transmitter_system_clock_pll} -quiet] -quiet
