# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/KANG Jian/Desktop/Underwater_OOK/Transmitter_Source_Code/ips/transmitter/transmitter.xci
# IP: The module: 'transmitter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/KANG Jian/Desktop/Underwater_OOK/Transmitter_Source_Code/ips/transmitter/transmitter.xdc
# XDC: The top module name and the constraint reference have the same name: 'transmitter'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/KANG Jian/Desktop/Underwater_OOK/Transmitter_Source_Code/ips/transmitter/transmitter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'transmitter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/KANG Jian/Desktop/Underwater_OOK/Transmitter_Source_Code/ips/transmitter/transmitter.xci
# IP: The module: 'transmitter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/KANG Jian/Desktop/Underwater_OOK/Transmitter_Source_Code/ips/transmitter/transmitter.xdc
# XDC: The top module name and the constraint reference have the same name: 'transmitter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/KANG Jian/Desktop/Underwater_OOK/Transmitter_Source_Code/ips/transmitter/transmitter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'transmitter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
